name: crypto-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.1.4
  - numpy>=1.26.2
  - statsmodels>=0.14.1
  - matplotlib>=3.8.2
  - scikit-learn>=1.3.2
  - pip
  - pip:
    - python-binance>=1.0.19
    - requests>=2.31.0 